name: native_flutter_admob
description: Admob native ad plugin for Flutter
version: 0.1.1+3
author: AliatiSoftware <suporte@aliatisoftware.com>
homepage: https://github.com/FinotiLucas/flutter_native_admob

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.nover.flutternativeadmob
    pluginClass: FlutterNativeAdmobPlugin

